apiVersion: v1
kind: Pod
metadata:
  name: "maven"
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: mavenn
    image: maven:3.6.1-jdk-8
    resources:
      limits:
        memory: "4000Mi"
      requests:
        memory: "2000Mi"
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: container-env-var-value
    volumeMounts:
    - name: pipeline-status-plugin
      mountPath: /pipeline-status-plugin
    - name: maven-cache
      mountPath: /root/.m2/repository
  volumes :
  - name: pipeline-status-plugin 
    hostPath:
      path: /Users/jonr/temp/pipeline-status-plugin
  - name: maven-cache
    hostPath:
      path: /Users/jonr/.m2/repository

